[package]
name = "tok2me"
version = "0.1.0"
authors = ["Andrew Strickland"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtok2me = {git = "https://github.com/andyslucky/libtok2me"}
clap = "3.0.0-beta.2"
